version: "3.8"
services:
  pyeth-proxy:
    image: ${IMAGE_TAG}
    container_name: pyeth-proxy
    ports:
      - "8000:8000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - RPC_PROVIDERS_HTTP=${RPC_PROVIDERS_HTTP}
      - TIMEOUT_SECONDS=${TIMEOUT_SECONDS}
